name: Go package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up GoLang ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - run: |
        go run concepts/1-hello-world.go
